language: java
sudo: false
services:
  - mongodb
jdk:
  - openjdk11
cache:
  directories:
    - '$HOME/.m2/repository'
install: true
before_script:
    $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk7 --target ${TRAVIS_HOME}/openjdk7
script:
    JAVA_HOME=${TRAVIS_HOME}/openjdk11 mvn clean compile site -Dmaven.test.skip=true -Djdk.home=${TRAVIS_HOME}/openjdk7 && JAVA_HOME=${TRAVIS_HOME}/openjdk7 mvn verify -Dmaven.main.skip
before_deploy:
  - mvn deploy -Dmaven.test.skip=true -Dmaven.install.skip=true -DaltDeploymentRepository=travis::default::file:target/deploy
deploy:
  provider: bintray
  file: target/descriptor.json
  user: fbacchella
  skip_cleanup: true
  on: release
  key:
    secure: T4HuK6dpvbq1IjRykbztA/m5PzGQs6o/Mg2fNujG+38TSWzd3858VwoHziP0P6TUMdmzhPsQrwWL0VKJrRv7bxm8XA5nM3tp40kc3O9x34nJVlWu5eIYsMZMz2G8WxuNd/5WpFqrGn+xUTpKmHlFFY+vyDwRn3ISYCplirwMORw=
notifications:
  irc:
  - irc.freenode.org#jrds
