language: java
sudo: false
services:
  - mongodb
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
cache:
  directories:
    - "$HOME/.m2"
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b5f5d5c337a7af9276
    on_success: change
    on_failure: always
    on_start: never
addons:
  sonarcloud:
    organization: rrd4j
    token:
      secure: "jQYJJtZwMLL584h/D3DMyF/N2GUHVucEAsH6EbvlPPhEkArZh97/HFOMLJhqxi/RRndpd0fVIUqwToIBfYepnkgZlsbLEVFztZoFqIWygCOu1rbTXVpU0mTX/dsxxzPyyJI3YhmvWQpwuKQrSk8DL9RUOr6niSbr9wgloPIPgtQ="
