language: java
sudo: false
services:
  - mongodb
jdk:
  - oraclejdk9
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b5f5d5c337a7af9276
    on_success: change
    on_failure: always
    on_start: never
