language: java
sudo: false
services:
  - mongodb
jdk:
  - openjdk11
cache:
  directories:
    - '$HOME/.m2/repository'
install: true
script:
  - mvn clean verify site -Dmaven.test.skip=true -Djdk.home=/usr/lib/jvm/java-7-openjdk-amd64 && JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64 mvn test -Dmaven.main.skip -Djdk.home=/usr/lib/jvm/java-7-openjdk-amd64 --settings deploy-settings.xml
before_deploy:
  - mvn deploy -Dmaven.test.skip=true -Dmaven.main.skip -Dmaven.install.skip=true -DaltDeploymentRepository=travis::default::file:target/deploy
deploy:
  provider: bintray
  file: target/descriptor.json
  user: fbacchella
  skip_cleanup: true
  on: release
  key:
    secure: T4HuK6dpvbq1IjRykbztA/m5PzGQs6o/Mg2fNujG+38TSWzd3858VwoHziP0P6TUMdmzhPsQrwWL0VKJrRv7bxm8XA5nM3tp40kc3O9x34nJVlWu5eIYsMZMz2G8WxuNd/5WpFqrGn+xUTpKmHlFFY+vyDwRn3ISYCplirwMORw=
notifications:
  irc:
  - irc.freenode.org#jrds
